[workspace]
members = [
    "frameworks/constants",
    "frameworks/definition",
    "frameworks/ipc",
    "frameworks/os_dependency/log",
    "frameworks/utils/hasher",
    "interfaces/kits/c",
    "services/core_service",
    "services/crypto_manager",
    "services/db_operator",
    "services/os_dependency",
    "test/unittest/inner_api_rust",
    "test/unittest/crypto_manager_test",
]
