[workspace]
members = [
    "frameworks/common",
    "frameworks/ipc_interface",
    "frameworks/ipc_proxy",
    "interfaces/kits/c",
    "services/core_service",
    "services/crypto_manager",
    "services/db_operator",
    "services/os_dependency",
    "test/unittest/inner_api_rust",
    "test/unittest/db_operator_test",
    "test/unittest/crypto_manager_test",
]
