[workspace]
members = [
    "frameworks/common",
    "frameworks/ipc_define",
    "interfaces/inner_api/rs",
    "services/core_service",
    "db_operator",
    "test/unittest/inner_api_rust",
    "services/crypto_manager",
]
