export default class CommonConstants{
  /**
   * The src msg.
   */
  static readonly SECOND_SRC_MSG: string = 'Index页面传来的数据';

  /**
   * The second page url.
   */
  static readonly SECOND_URL: string = 'pages/searchPage';

  /**
   * The second page message.
   */
  static readonly SECOND_MESSAGE: string = 'Search Page';

  /**
   * The src param.
   */
  static readonly SECOND_SRC_PARAM: string = 'src';
}